AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 900
    MemorySize: 10240

Resources:
  SyncFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_OUTPUT_PREFIX: textract-output
          S3_OUTPUT_BUCKET: simplesearchpdf-textractsimpleasyncworkflow2d7d5b-j392r3sveake
          LOG_LEVEL: DEBUG
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.9-v1

